services:
    nginx:
        image: nginx:alpine
        container_name: app_nginx
        restart: unless-stopped
        ports:
            - "3000:80"
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        depends_on:
            -   app
        networks:
            - app_network

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: app
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www/
        depends_on:
            -   postgres
        networks:
            - app_network

    postgres:
        image: postgres:latest
        container_name: app_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5433:${DB_PORT}"
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
        networks:
            - app_network

    adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
            - "8080:8080"
        environment:
            ADMINER_DEFAULT_DB_DRIVER: ${DB_CONNECTION}
            ADMINER_DEFAULT_DB_HOST: ${DB_HOST}:${DB_PORT}
            ADMINER_DEFAULT_DB_NAME: ${DB_DATABASE}
            ADMINER_DESIGN: nette
            ADMINER_DEFAULT_SERVER: ${DB_HOST}:${DB_PORT}
        depends_on:
            -   postgres
        networks:
            - app_network


networks:
    app_network:
        driver: bridge

volumes:
    pgdata:
        driver: local
